<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.39.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="libBSP">
      <HintPath>Dependencies\libBSP.dll</HintPath>
    </Reference>
    <Reference Include="sourcepp">
      <HintPath>Dependencies/sourcepp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\materials\tools\toolsinvisibledisplacement.vmt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\materials\tools\toolsinvisibledisplacement.vtf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\materials\tools\envmapinvisible.vtf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\DevIL.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\HLLib.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\libBSP.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies/sourcepp.dll">
      <Link>sourcepp.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Q3Content\instructions.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="CustomContent\readme.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('win')) Or ($(RuntimeIdentifier) == '' And $([MSBuild]::IsOSPlatform('Windows')))">
    <None Include="Dependencies\sourcepp_win\sourcepp_sourceppc.dll">
      <Link>sourcepp_sourceppc.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Dependencies\sourcepp_win\sourcepp_vtfppc.dll">
      <Link>sourcepp_vtfppc.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux')) Or ($(RuntimeIdentifier) == '' And $([MSBuild]::IsOSPlatform('Linux')))">
    <None Include="../BSPConvert.Lib/Dependencies/sourcepp_linux/sourcepp_sourceppc.so">
      <Link>sourcepp_sourceppc.so</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Dependencies/sourcepp_linux/sourcepp_vtfppc.so">
      <Link>sourcepp_vtfppc.so</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
